# Generated by Django 5.2.9 on 2025-12-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_scrapeaction_business_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
